### ISSUE TITLE
Visibly show map on set_point page

### ISSUE THREAD

**Issue by SpookyMiso** [devleague/jog-it-off#12]
OBJECTIVE:

Make map display using angular-meteor

---

PROBLEM:

9/19/2015: Currently can't see map displayed on set_point.ng.html page. Trying to use angular code to display map but proving difficult

(UPDATE) 9/19/2015: Currently displaying, but error messages show within console. Initially thought that we needed a key to use google maps api, but not necessary. 

Error message shown below:
![](https://s3.amazonaws.com/uploads.hipchat.com/54891/589476/mFc0A4MoSevGiy2/Screen%20Shot%202015-09-21%20at%2010.10.43%20PM.png)

---

STEPS NEEDED TO GET THERE:

1) Need to remove all error messages pertaining to ngTransclude

---

END RESULT:

![screen shot 2015-09-21 at 7 46 14 pm](https://cloud.githubusercontent.com/assets/11057429/10011664/735ebbe6-6099-11e5-81b5-9cad06b2a0cb.png)

**Comment by mdctenga** [comment]
Passed along to Cannon. closing issue
