### ISSUE TITLE
Geofencing

### ISSUE THREAD

**Issue by rcgmcloud** [devleague/jog-it-off#2]
Research best method of geofencing and how to apply it to the project.

**Comment by rcgmcloud** [comment]
research compatible, easy, or efficient plugin 
-or-
 decide if we should use geolocation and manually set our own geofence algorithm 
- set current coordinate to be geofence
- save value to db
- show up on map

**Comment by SpookyMiso** [comment]
Implementing custom geo-fencing via geo-location

Set-up an algorithm to calculate distance from geo-location
