### ISSUE TITLE
The initial refresh of map display needs to be removed or refresh sooner

### ISSUE THREAD

**Issue by rcgmcloud** [devleague/jog-it-off#21]
The map still displays default location to downtown Honolulu. refreshes though after 5-8 seconds.  Point markers should not be placed within those "pre-refresh" display.  Without the initial default location though, the map doesn't seem to show.  One suggestion for a quicker solution is to set the interval to loop at a faster duration, although that could slow the app even more.  Please figure out a solution!

**Comment by cannonbrooke** [comment]
Going to try to set it for an earlier refresh.

**Comment by cannonbrooke** [comment]
Ray got this bad boy to work. There is a 2-5 delay but we are going to deal with it.
- cannon

**Comment by cannonbrooke** [comment]
closing
