### ISSUE TITLE
The pickUp Marker fn seems to have a faulty relationship with the map

### ISSUE THREAD

**Issue by rcgmcloud** [devleague/jog-it-off#22]
We are having issues getting the proper response when picking up point markers. I believe the code for the pick up validations are fine because I have seen all/most alert possibilities show ("you cannot pick up your own marker", "you are not near enough to a marker", "finish, good job", "you got a coin!").  This is why it leads me to believe it is a map response issue.  

Sometimes when I try to pick up someone's marker and I'm exactly on their spot, it will give an unexpected response, such as, "You are not close enough"  or "you cannot pick up your own location".  We need to figure out why these unexpected responses show up.

**Comment by mdctenga** [comment]
Implemented a new findClosestMarker fn
