### ISSUE TITLE
Create more descriptive issues from now on

### ISSUE THREAD

**Issue by theRemix** [devleague/jog-it-off#8]
@rcgmcloud great job on putting bulleted descriptions/requirements in tasks.
Now start to make the Titles of the tasks more descriptive as well.

for example, here's how github alerts look 

![example](http://i.imgur.com/eES6VW8.png)

acknowledge by closing this issue.
keep up the good work!

**Comment by mdctenga** [comment]
Cleaning out old tickets. Acknowledged.
